TRAIN:
  # LOAD_WEIGHT_PATH: '.tmp_results/2021-05-03_11-50-24/weights.ckpt'
  LOAD_WEIGHT_PATH: ''
  # [ae_weight, clf_weight]
  LOSS_WEIGHT: [0, 1.]
  # LOSS_WEIGHT: [1, 0]
  MODEL_TYPE: 'convae_classifier'
  MOMENTUM: 0.9
  NUM_EPOCHS: 300
  OPTIMIZER_TYPE: 'sgd'
